name: Publish Package to npmjs
on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubicloud-standard-2-ubuntu-2404
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.orog'
      - run: npm i -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
